on: [push, pull_request]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    strategy:
       fail-fast: false
       matrix:
         os:
            - { prettyname: Windows, fullname: windows-latest }
            - { prettyname: macOS, fullname: macos-latest }
            - { prettyname: Linux, fullname: ubuntu-latest }
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
    
    # https://github.com/ppy/osu-framework/issues/4349
    - name: Install libavformat-dev
      if: ${{matrix.os.fullname == 'ubuntu-latest'}}
      run: |
       sudo apt-get update && \
       sudo apt-get -y install libavformat-dev
    
    - name: Restore dependencies
      run: dotnet restore
    
    # Build on iOS is failes so we need to allow continue-on-error
    - name: Build
      run: |
        cd maisim
        dotnet build -c Debug maisim.Desktop.slnf
    
    - name: Test
      run: |
        cd maisim
        dotnet test maisim.Desktop.slnf
      shell: pwsh
